// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoBufDTO.proto

package com.hzk.proto;

public interface CDubboGooglePBResponseTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hzk.proto.CDubboGooglePBResponseType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
