// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoBufDTO.proto

package com.hzk.proto;

public interface CDubboGooglePBRequestTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hzk.proto.CDubboGooglePBRequestType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double double = 1;</code>
   */
  double getDouble();

  /**
   * <code>float float = 2;</code>
   */
  float getFloat();

  /**
   * <code>int32 int32 = 3;</code>
   */
  int getInt32();

  /**
   * <code>bool bool = 13;</code>
   */
  boolean getBool();

  /**
   * <code>string string = 14;</code>
   */
  String getString();
  /**
   * <code>string string = 14;</code>
   */
  com.google.protobuf.ByteString
      getStringBytes();

  /**
   * <code>bytes bytesType = 15;</code>
   */
  com.google.protobuf.ByteString getBytesType();
}
