// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoBufDTO.proto

package com.hzk.proto;

public final class ProtoBufDTO {
  private ProtoBufDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hzk_proto_CDubboGooglePBRequestType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hzk_proto_CDubboGooglePBRequestType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hzk_proto_CDubboGooglePBResponseType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hzk_proto_CDubboGooglePBResponseType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021protoBufDTO.proto\022\rcom.hzk.proto\"z\n\031CD" +
      "ubboGooglePBRequestType\022\016\n\006double\030\001 \001(\001\022" +
      "\r\n\005float\030\002 \001(\002\022\r\n\005int32\030\003 \001(\005\022\014\n\004bool\030\r " +
      "\001(\010\022\016\n\006string\030\016 \001(\t\022\021\n\tbytesType\030\017 \001(\014\")" +
      "\n\032CDubboGooglePBResponseType\022\013\n\003msg\030\001 \001(" +
      "\t2x\n\025CDubboGooglePBService\022_\n\010sayHello\022(" +
      ".com.hzk.proto.CDubboGooglePBRequestType" +
      "\032).com.hzk.proto.CDubboGooglePBResponseT" +
      "ypeB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hzk_proto_CDubboGooglePBRequestType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hzk_proto_CDubboGooglePBRequestType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hzk_proto_CDubboGooglePBRequestType_descriptor,
        new String[] { "Double", "Float", "Int32", "Bool", "String", "BytesType", });
    internal_static_com_hzk_proto_CDubboGooglePBResponseType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hzk_proto_CDubboGooglePBResponseType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hzk_proto_CDubboGooglePBResponseType_descriptor,
        new String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
